### ISSUE TITLE
Bug - Class naming

### ISSUE THREAD

**Issue by siemato** [MadnessLabs/MadnessEnjinCLI#3]
description:
when generating a component with multiple dashes, the Class receives a dash as well

current behavior:
`enjin ac namespace-component-name` --> `export class NamespaceComponent-name`

expected behavior:
`enjin ac namespace-component-name` --> `export class NamespaceComponentName`

comments:
namespacing components is considered good behavior (st-componentname, st-componentname1-name2) and is officially encouraged. Especially in Stencil, where you create bundles like: st-card+st-card-light+st-card-dark.

**Comment by popcorn245** [comment]
I will make sure this makes it into v1.1.7 this week. I will also consider assuming namespace based on stencil config.
