### ISSUE TITLE
"enjin ac" rewrite stencil.config.js

### ISSUE THREAD

**Issue by caiquelsousa** [MadnessLabs/MadnessEnjinCLI#4]
Hi! Good job on this repo!
I'm having a problem with "enjin ac", every time that I use, it rewrite the entire file stencil.config.js so for example:

**I have:**
```
const sass = require('@stencil/sass');

exports.config = {
  "serviceWorker": {
    "swSrc": "src/sw.js"
  },
  "globalStyle": "src/global/app.css",
  "plugins": [
    sass() //<-----
  ]
};
```
**It becomes:**
```
const sass = require('@stencil/sass');

exports.config = {
  "serviceWorker": {
    "swSrc": "src/sw.js"
  },
  "globalStyle": "src/global/app.css",
  "plugins": [
    {
      "name": "sass" //<-----
    }
  ]
};
```
So every time that i use this command I have to change it again...
Can you help me with this?

**Comment by popcorn245** [comment]
@caiquelsousa thanks for filing as issue about this.  After they broke stencil-sass into it's own project it broke our add component command.  I will fix it in the next couple days and let you know here when it's live. Thanks again! ^_^

**Comment by popcorn245** [comment]
@caiquelsousa Just pushed a fix, please update your EnjinCLI by running the following and feel free to comment if it still isn't working.

```
npm install -g madnessenjincli
```

Should be on version 1.1.12, happy hacking! ^_^

PS - Bundles are no longer needed in the stencil.config.js file, it automagically figures it out, only use the bundles if you need to optimize the build.
